-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."personnel" add column "personnel_category_id_second" uuid
--  null;
